### PR TITLE
BaSP-MR-25: Hotfix Trainers put

### PR DESCRIPTION
**Pull request by IgnacioGalceran**
App crash fixed in Trainers update controller. Returns added to the res.status.json.

### CODE REVIEW

**Review by Micaela-Rossi — APPROVED** [review]
I tested and it works correctly, when you put an invalid id doesn't crash, only show you the error. Same when you put an id that  doesn't exist.

**Review by CavalloFede — APPROVED** [review]
Tested and working

**Review by Eliezer-Alberto — APPROVED** [review]
Everything tested and working correctly..

**Review by nailaghigo — APPROVED** [review]
🚀

**Pull request merged**
