### PR TITLE
BaSP-MR-18: HotFix Members put 

### PR DESCRIPTION
**Pull request by CavalloFede**
Fixed members put by moving the .then() to the line 169

### CODE REVIEW

**Review by Micaela-Rossi — APPROVED** [review]
Tested! Doesn't crash.

**Review by IgnacioGalceran — APPROVED** [review]
Everything's right

**Review by Eliezer-Alberto — APPROVED** [review]
It is all fine!..

**Review by nailaghigo — APPROVED** [review]
🚀

**Pull request merged**
