### PR TITLE
BaSP-MR-24: HotFix Trainers delete

### PR DESCRIPTION
**Pull request by francoax**
Fixed bug on delete method that crashed the app.

Problem:  the app were sending two responses at the same time.

### CODE REVIEW

**Review by IgnacioGalceran — APPROVED** [review]
I did the tests and everything works fine

**Review by CavalloFede — APPROVED** [review]

**Review by Micaela-Rossi — APPROVED** [review]
Tested, all ok!

**Review by Eliezer-Alberto — APPROVED** [review]
Everything works well..

**Review by nailaghigo — APPROVED** [review]
💯

**Review by nailaghigo — APPROVED** [review]
💯

**Pull request merged**
