### PR TITLE
BaSP-MR-23: HOTFIX Super Admin, post.

### PR DESCRIPTION
**Pull request by Micaela-Rossi**
Changed the function to async to correctly functionality, now if you create a new super admin with an existing email gives you error but don't break the console and the app.

### CODE REVIEW

**Review by IgnacioGalceran — APPROVED** [review]
I did the tests and everything works fine

**Review by CavalloFede — APPROVED** [review]
Tested the changes, all works fine

**Review by Eliezer-Alberto — APPROVED** [review]
Everything works correctly..

**Review by nailaghigo — APPROVED** [review]
🚀

**Pull request merged**
