### PR TITLE
BaSP - MR-20:HotFix-Activity-Delete

### PR DESCRIPTION
**Pull request by CavalloFede**
Fixed delete endpoint on activity controller

### CODE REVIEW

**Review by IvanJukonis — APPROVED** [review]
The HOTFIX has been corrected successfully. The solution has no errors.

**Review by Eliezer-Alberto — APPROVED** [review]
The endpoin fixed works correctly..

**Review by IgnacioGalceran — APPROVED** [review]
Everything fine. Delete endpoint has no errors.

**Review by nailaghigo — APPROVED** [review]
🚀

**Pull request merged**
